local _M = {}

_M.towerButton = "Tower"
_M.pathButton = "Path"
_M.minionButton = "Minion"
_M.pathBuildingInstructions = "Instructions:\nTap empty cells to build a path, tap the current end to remove it. The blue tile is the enemy base, the red one is yours. Minimum path length is 4 tiles.\n\nTap the map to begin."
_M.proceedToGameButton = "Done!"
_M.proceedToAddVisualsButton = "Add visuals"
_M.quickGameButton = "QuickGame!"
_M.backToPathBuildingInterfaceButton = "Back"
_M.pathTooShort = "Path too short!"
_M.startGameButton = "Start Game!"
_M.startGameOverlayText = "When you are ready for the first wave, press 'Start Game!'"
_M.addVisualsInstructions = "Drag and drop visual objects onto the map. These do not affect gameplay, but can help you relate the game world to the real environment."
_M.gameCountdownText = "The game is about to begin!\nFirst wave in "
_M.waveCountdownText = "Next wave in "
_M.waveComingText = "Next wave coming!"
_M.baseDestroyed = "Base destroyed! :("
_M.restartGameButton = "Restart wave!"
_M.nextWaveText = "Next wave in "
_M.startWaveButton = "Start Wave! Earn "
_M.upgradeTowerButton = "Upgrade"
_M.sellTowerButton = "Sell"
_M.upgradeDamage = "Damage"
_M.upgradeSlow = "Slow"
_M.upgradeRange = "Range"
_M.cancelSaleButton = "Cancel"
_M.confirmSaleButton = "Confirm"
_M.cancelUpgradeButton = "Cancel"
_M.confirmUpgradeButton = "Confirm"
_M.sellAndUpgradeInstructions = "Tap a tower to sell or upgrade."
_M.upgradeTowerUnavailable = "Tower at max level!"
_M.fastForwardButton = ">>"
_M.pauseButton = "Pause"
_M.level = "Level "
_M.complete = " Complete!"

return _M